name = "fixtweet"
account_id = "[CLOUDFLARE_ACCOUNT_ID]"
main = "./dist/worker.js"
compatibility_date = "2022-08-17"
send_metrics = false
services = [
  { binding = "TwitterProxy", service = "elongator" }
]

[build]
command = "npm run build"

[miniflare.globals]
TEST = "true" # Will have unicode character errors in headers if not set to true